/*
 * HOMEROOM — the members-only layer.
 *
 * Everything here is namespaced `hr_` and hangs off the shared `users` table,
 * so one handle logs you into both the news feed and the network. Written as
 * one idempotent DDL string for the same reason the news schema is: migrations
 * on a single-file database are a `CREATE TABLE IF NOT EXISTS` away.
 */

export const HOMEROOM_SCHEMA = `
/* ---------------------------------------------------------------- members */

CREATE TABLE IF NOT EXISTS hr_members (
  user_id      TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  name         TEXT NOT NULL DEFAULT '',
  headline     TEXT NOT NULL DEFAULT '',
  org          TEXT NOT NULL DEFAULT '',
  role         TEXT NOT NULL DEFAULT '',
  cohort       TEXT,
  location     TEXT NOT NULL DEFAULT '',
  bio          TEXT NOT NULL DEFAULT '',
  working_on   TEXT NOT NULL DEFAULT '',
  ask_me_about TEXT NOT NULL DEFAULT '',
  links        TEXT NOT NULL DEFAULT '',
  bsl          TEXT,
  open_intros  INTEGER NOT NULL DEFAULT 1,
  open_hours   INTEGER NOT NULL DEFAULT 0,
  open_collab  INTEGER NOT NULL DEFAULT 1,
  open_hiring  INTEGER NOT NULL DEFAULT 0,
  joined_at    BIGINT NOT NULL,
  updated_at   BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_bf_members_cohort ON hr_members(cohort);

CREATE TABLE IF NOT EXISTS hr_expertise (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tag     TEXT NOT NULL,
  PRIMARY KEY (user_id, tag)
);

CREATE INDEX IF NOT EXISTS idx_bf_expertise_tag ON hr_expertise(tag);

/* ------------------------------------------------------------------- labs */

CREATE TABLE IF NOT EXISTS hr_orgs (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  tagline     TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  kind        TEXT NOT NULL DEFAULT 'startup',
  stage       TEXT NOT NULL DEFAULT 'idea',
  location    TEXT NOT NULL DEFAULT '',
  website     TEXT,
  cohort      TEXT,
  founded     INTEGER,
  headcount   INTEGER,
  tags        TEXT NOT NULL DEFAULT '',
  created_by  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bf_orgs_kind ON hr_orgs(kind);

CREATE TABLE IF NOT EXISTS hr_org_members (
  org_id  INTEGER NOT NULL REFERENCES hr_orgs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role    TEXT NOT NULL DEFAULT '',
  admin   INTEGER NOT NULL DEFAULT 0,
  joined_at BIGINT NOT NULL,
  PRIMARY KEY (org_id, user_id)
);

/* Weekly-ish progress notes, the "company update" of the reskin. */
CREATE TABLE IF NOT EXISTS hr_updates (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  org_id     INTEGER NOT NULL REFERENCES hr_orgs(id) ON DELETE CASCADE,
  author_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  period     TEXT NOT NULL DEFAULT '',
  body       TEXT NOT NULL,
  asks       TEXT NOT NULL DEFAULT '',
  metrics    TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bf_updates_org ON hr_updates(org_id, created_at DESC);

/* ------------------------------------------------------------------ deals */

CREATE TABLE IF NOT EXISTS hr_deals (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug        TEXT NOT NULL UNIQUE,
  vendor      TEXT NOT NULL,
  title       TEXT NOT NULL,
  category    TEXT NOT NULL DEFAULT 'other',
  summary     TEXT NOT NULL DEFAULT '',
  details     TEXT NOT NULL DEFAULT '',
  worth       TEXT NOT NULL DEFAULT '',
  code        TEXT NOT NULL DEFAULT '',
  url         TEXT,
  expires_at  BIGINT,
  active      INTEGER NOT NULL DEFAULT 1,
  posted_by   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS hr_deal_claims (
  deal_id    INTEGER NOT NULL REFERENCES hr_deals(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at BIGINT NOT NULL,
  PRIMARY KEY (deal_id, user_id)
);

/* ---------------------------------------------------------------- funders */

CREATE TABLE IF NOT EXISTS hr_funders (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL DEFAULT 'vc',
  focus       TEXT NOT NULL DEFAULT '',
  stages      TEXT NOT NULL DEFAULT '',
  check_size  TEXT NOT NULL DEFAULT '',
  location    TEXT NOT NULL DEFAULT '',
  website     TEXT,
  description TEXT NOT NULL DEFAULT '',
  dilutive    INTEGER NOT NULL DEFAULT 1,
  added_by    TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at  BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bf_funders_kind ON hr_funders(kind);

/* Five stars and a written account, the way Bookface does it. One per member. */
CREATE TABLE IF NOT EXISTS hr_funder_reviews (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  funder_id   INTEGER NOT NULL REFERENCES hr_funders(id) ON DELETE CASCADE,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  speed       INTEGER,
  value_add   INTEGER,
  invested    INTEGER NOT NULL DEFAULT 0,
  anonymous   INTEGER NOT NULL DEFAULT 1,
  body        TEXT NOT NULL DEFAULT '',
  created_at  BIGINT NOT NULL,
  UNIQUE (funder_id, user_id)
);

/* The fundraising CRM: one row per funder you are tracking. */
CREATE TABLE IF NOT EXISTS hr_pipeline (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  funder_id  INTEGER NOT NULL REFERENCES hr_funders(id) ON DELETE CASCADE,
  org_id     INTEGER REFERENCES hr_orgs(id) ON DELETE SET NULL,
  status     TEXT NOT NULL DEFAULT 'researching',
  amount     TEXT NOT NULL DEFAULT '',
  notes      TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE (user_id, funder_id)
);

/* ----------------------------------------------------------- office hours */

CREATE TABLE IF NOT EXISTS hr_slots (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  host_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  format      TEXT NOT NULL DEFAULT 'one-on-one' CHECK (format IN ('one-on-one','group')),
  starts_at   BIGINT NOT NULL,
  minutes     INTEGER NOT NULL DEFAULT 30,
  capacity    INTEGER NOT NULL DEFAULT 1,
  place       TEXT NOT NULL DEFAULT '',
  topics      TEXT NOT NULL DEFAULT '',
  canceled    INTEGER NOT NULL DEFAULT 0,
  created_at  BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bf_slots_start ON hr_slots(starts_at);

CREATE TABLE IF NOT EXISTS hr_bookings (
  slot_id    INTEGER NOT NULL REFERENCES hr_slots(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  question   TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  PRIMARY KEY (slot_id, user_id)
);

/* ------------------------------------------------------------------- jobs */

CREATE TABLE IF NOT EXISTS hr_jobs (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  org_id      INTEGER NOT NULL REFERENCES hr_orgs(id) ON DELETE CASCADE,
  posted_by   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  discipline  TEXT NOT NULL DEFAULT 'other',
  employment  TEXT NOT NULL DEFAULT 'full-time',
  location    TEXT NOT NULL DEFAULT '',
  remote      INTEGER NOT NULL DEFAULT 0,
  comp        TEXT NOT NULL DEFAULT '',
  equity      TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  tags        TEXT NOT NULL DEFAULT '',
  closed      INTEGER NOT NULL DEFAULT 0,
  created_at  BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bf_jobs_org ON hr_jobs(org_id);

CREATE TABLE IF NOT EXISTS hr_applications (
  job_id     INTEGER NOT NULL REFERENCES hr_jobs(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  note       TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  PRIMARY KEY (job_id, user_id)
);

/* ----------------------------------------------------------------- events */

CREATE TABLE IF NOT EXISTS hr_events (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  host_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  kind        TEXT NOT NULL DEFAULT 'meetup',
  starts_at   BIGINT NOT NULL,
  minutes     INTEGER NOT NULL DEFAULT 90,
  place       TEXT NOT NULL DEFAULT '',
  url         TEXT,
  capacity    INTEGER NOT NULL DEFAULT 0,
  canceled    INTEGER NOT NULL DEFAULT 0,
  created_at  BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bf_events_start ON hr_events(starts_at);

CREATE TABLE IF NOT EXISTS hr_rsvps (
  event_id   INTEGER NOT NULL REFERENCES hr_events(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status     TEXT NOT NULL DEFAULT 'going',
  created_at BIGINT NOT NULL,
  PRIMARY KEY (event_id, user_id)
);

/* ---------------------------------------------------------------- library */

CREATE TABLE IF NOT EXISTS hr_library (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug       TEXT NOT NULL UNIQUE,
  title      TEXT NOT NULL,
  kind       TEXT NOT NULL DEFAULT 'guide',
  summary    TEXT NOT NULL DEFAULT '',
  body       TEXT NOT NULL DEFAULT '',
  tags       TEXT NOT NULL DEFAULT '',
  author_id  TEXT REFERENCES users(id) ON DELETE SET NULL,
  reads      INTEGER NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

/* ----------------------------------------------------------------- intros */

CREATE TABLE IF NOT EXISTS hr_intros (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  requester_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason       TEXT NOT NULL DEFAULT '',
  status       TEXT NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','accepted','declined')),
  created_at   BIGINT NOT NULL,
  resolved_at  BIGINT
);

CREATE INDEX IF NOT EXISTS idx_bf_intros_target ON hr_intros(target_id, status);

/* --------------------------------------------------------------- messages */

CREATE TABLE IF NOT EXISTS hr_threads (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject    TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at BIGINT NOT NULL,
  last_at    BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS hr_thread_members (
  thread_id    INTEGER NOT NULL REFERENCES hr_threads(id) ON DELETE CASCADE,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_at BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (thread_id, user_id)
);

CREATE TABLE IF NOT EXISTS hr_messages (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  thread_id  INTEGER NOT NULL REFERENCES hr_threads(id) ON DELETE CASCADE,
  sender_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body       TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bf_messages_thread ON hr_messages(thread_id, created_at);

/* ---------------------------------------------------------- notifications */

CREATE TABLE IF NOT EXISTS hr_notifications (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind       TEXT NOT NULL,
  actor_id   TEXT REFERENCES users(id) ON DELETE SET NULL,
  text       TEXT NOT NULL DEFAULT '',
  href       TEXT NOT NULL DEFAULT '/homeroom',
  read_at    BIGINT,
  created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bf_notifications_user ON hr_notifications(user_id, created_at DESC);

/* --------------------------------------------------------------- yearbook */

/* The founder wall: the parts of a profile that belong to a cohort rather than
   to a directory row. Kept off hr_members so a yearbook entry can stand for a
   past cohort without implying the profile is still current. */
CREATE TABLE IF NOT EXISTS hr_yearbook (
  user_id     TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  cohort      TEXT NOT NULL DEFAULT '',
  house       TEXT NOT NULL DEFAULT '',
  venture     TEXT NOT NULL DEFAULT '',
  one_liner   TEXT NOT NULL DEFAULT '',
  quote       TEXT NOT NULL DEFAULT '',
  building    TEXT NOT NULL DEFAULT '',
  before_haus TEXT NOT NULL DEFAULT '',
  photo_url   TEXT NOT NULL DEFAULT '',
  site_url    TEXT NOT NULL DEFAULT '',
  featured    INTEGER NOT NULL DEFAULT 0,
  updated_at  BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hr_yearbook_cohort ON hr_yearbook(cohort);

/* A signature in someone's yearbook. Short, visible to members, and not a DM —
   the point is that the rest of the cohort can read it. */
CREATE TABLE IF NOT EXISTS hr_signatures (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  author_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body       TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  UNIQUE (user_id, author_id)
);

/* ------------------------------------------------------------------ atlas */

CREATE TABLE IF NOT EXISTS hr_atlas (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug         TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  city         TEXT NOT NULL DEFAULT '',
  country      TEXT NOT NULL DEFAULT '',
  region       TEXT NOT NULL DEFAULT '',
  kind         TEXT NOT NULL DEFAULT 'community',
  status       TEXT NOT NULL DEFAULT 'unknown'
               CHECK (status IN ('active','limited','dormant','unknown')),
  bsl          TEXT NOT NULL DEFAULT '',
  website      TEXT,
  capabilities TEXT NOT NULL DEFAULT '',
  note         TEXT NOT NULL DEFAULT '',
  source       TEXT NOT NULL DEFAULT '',
  confirmed_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  confirmed_at BIGINT,
  created_at   BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hr_atlas_region ON hr_atlas(region, status);

/* "I was there in March and it is open." Worth more than any directory. */
CREATE TABLE IF NOT EXISTS hr_atlas_reports (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  lab_id     INTEGER NOT NULL REFERENCES hr_atlas(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status     TEXT NOT NULL,
  body       TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hr_atlas_reports ON hr_atlas_reports(lab_id, created_at DESC);

/* ---------------------------------------------------------------- mentors */

CREATE TABLE IF NOT EXISTS hr_mentors (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug        TEXT NOT NULL UNIQUE,
  user_id     TEXT REFERENCES users(id) ON DELETE SET NULL,
  name        TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT '',
  org         TEXT NOT NULL DEFAULT '',
  track       TEXT NOT NULL DEFAULT 'founder',
  tags        TEXT NOT NULL DEFAULT '',
  location    TEXT NOT NULL DEFAULT '',
  bio         TEXT NOT NULL DEFAULT '',
  format      TEXT NOT NULL DEFAULT 'one-on-one',
  scheduler   TEXT NOT NULL DEFAULT '',
  vetted      INTEGER NOT NULL DEFAULT 0,
  active      INTEGER NOT NULL DEFAULT 1,
  sessions    INTEGER NOT NULL DEFAULT 0,
  source      TEXT NOT NULL DEFAULT 'seed',
  created_at  BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hr_mentors_track ON hr_mentors(track, vetted DESC);

/* ------------------------------------------------------- funder reviews++ */

/* Rate My Funder: a review gets replies, because one bad experience is an
   anecdote and three replies saying the same thing is a pattern. */
CREATE TABLE IF NOT EXISTS hr_review_comments (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  review_id  INTEGER NOT NULL REFERENCES hr_funder_reviews(id) ON DELETE CASCADE,
  author_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body       TEXT NOT NULL,
  anonymous  INTEGER NOT NULL DEFAULT 0,
  deleted    INTEGER NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hr_review_comments ON hr_review_comments(review_id, created_at);

/* "This matches my experience" — the helpful vote, and the thing that sorts
   the review list. */
CREATE TABLE IF NOT EXISTS hr_review_votes (
  review_id  INTEGER NOT NULL REFERENCES hr_funder_reviews(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  helpful    INTEGER NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL,
  PRIMARY KEY (review_id, user_id)
);

/* ----------------------------------------------------------- the library+ */

CREATE TABLE IF NOT EXISTS hr_tracks (
  slug     TEXT PRIMARY KEY,
  title    TEXT NOT NULL,
  focus    TEXT NOT NULL DEFAULT '',
  blurb    TEXT NOT NULL DEFAULT '',
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS hr_modules (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug        TEXT NOT NULL UNIQUE,
  track       TEXT NOT NULL REFERENCES hr_tracks(slug) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  kind        TEXT NOT NULL DEFAULT 'playbook',
  summary     TEXT NOT NULL DEFAULT '',
  outcomes    TEXT NOT NULL DEFAULT '',
  work        TEXT NOT NULL DEFAULT '',
  deliverable TEXT NOT NULL DEFAULT '',
  minutes     INTEGER NOT NULL DEFAULT 45,
  week        INTEGER NOT NULL DEFAULT 0,
  position    INTEGER NOT NULL DEFAULT 0,
  reads       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_hr_modules_track ON hr_modules(track, position);

/* Progress is per member and per module, and "done" means the deliverable
   exists — which is why there is a note and a link, not just a checkbox. */
CREATE TABLE IF NOT EXISTS hr_progress (
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  module_id  INTEGER NOT NULL REFERENCES hr_modules(id) ON DELETE CASCADE,
  state      TEXT NOT NULL DEFAULT 'started'
             CHECK (state IN ('started','done')),
  note       TEXT NOT NULL DEFAULT '',
  link       TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, module_id)
);

/* ------------------------------------------------------------ events sync */

/* Set on any event that came from a Luma calendar, so a re-sync updates the
   row it already created rather than adding a second copy of the same event. */
CREATE TABLE IF NOT EXISTS hr_event_sources (
  event_id    INTEGER PRIMARY KEY REFERENCES hr_events(id) ON DELETE CASCADE,
  source      TEXT NOT NULL DEFAULT 'luma',
  external_id TEXT NOT NULL,
  url         TEXT NOT NULL DEFAULT '',
  synced_at   BIGINT NOT NULL,
  UNIQUE (source, external_id)
);

/* ------------------------------------------------------- news via Supabase */

/* The local receipt for something a member sent to the public feed at
   haus.fund/news. The canonical row lives in Supabase; this one exists so a
   member can see the state of their own submission even when Supabase is
   unreachable, which over a network it sometimes is. */
CREATE TABLE IF NOT EXISTS hr_news_submissions (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  remote_id    TEXT,
  title        TEXT NOT NULL,
  url          TEXT NOT NULL DEFAULT '',
  body         TEXT NOT NULL DEFAULT '',
  topic        TEXT NOT NULL DEFAULT 'general',
  status       TEXT NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','queued','published','rejected','failed')),
  error        TEXT NOT NULL DEFAULT '',
  created_at   BIGINT NOT NULL,
  updated_at   BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hr_news_user ON hr_news_submissions(user_id, created_at DESC);

/* ----------------------------------------------------------------- roster */

/* Who the Airtable said was in the programme, and when we last asked.
   The address is stored as a SHA-256 and never in the clear: a copy of this
   database should not also be a copy of the resident list. "masked" keeps
   enough for a steward to recognise a row ("el****@haus.fund") without it
   being a list of addresses. */
CREATE TABLE IF NOT EXISTS hr_roster (
  email_hash    TEXT PRIMARY KEY,
  masked        TEXT NOT NULL DEFAULT '',
  verdict       TEXT NOT NULL DEFAULT 'deny'
                CHECK (verdict IN ('allow','deny','review','error')),
  reason        TEXT NOT NULL DEFAULT '',
  name          TEXT NOT NULL DEFAULT '',
  cohort        TEXT NOT NULL DEFAULT '',
  house         TEXT NOT NULL DEFAULT '',
  status        TEXT NOT NULL DEFAULT '',
  lifecycle     TEXT NOT NULL DEFAULT '',
  resident_type TEXT NOT NULL DEFAULT '',
  user_id       TEXT REFERENCES users(id) ON DELETE SET NULL,
  attempts      INTEGER NOT NULL DEFAULT 1,
  checked_at    BIGINT NOT NULL,
  /* A steward resolving a "review" by hand. Their decision outranks the rule
     until the Airtable itself changes. */
  decided_by    TEXT REFERENCES users(id) ON DELETE SET NULL,
  decided_at    BIGINT,
  decision      TEXT CHECK (decision IN ('allow','deny')),
  note          TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_hr_roster_verdict ON hr_roster(verdict, checked_at DESC);

/* ---------------------------------------------------------------- invites */

/* The local fallback for onboarding invites. The real store is Supabase, because
   Supabase's copy carries RLS and security definer functions, so an invite can
   be redeemed there without this app holding a privileged credential — see
   app/invites.js. This table is the fallback, and durable in its own right now
   that the database is.

   The token is never stored, only its SHA-256, so the rows here are as useless
   to a reader as the ones in Supabase. */
CREATE TABLE IF NOT EXISTS hr_invites (
  id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  token_hash     TEXT NOT NULL UNIQUE,
  email          TEXT NOT NULL,
  invited_by     TEXT NOT NULL,
  note           TEXT NOT NULL DEFAULT '',
  roster_verdict TEXT NOT NULL DEFAULT '',
  status         TEXT NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','redeemed','revoked')),
  redeemed_by    TEXT,
  redeemed_at    BIGINT,
  expires_at     BIGINT NOT NULL,
  created_at     BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hr_invites_status ON hr_invites(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hr_invites_email  ON hr_invites(email);
`;
